# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-07-31 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='readprogress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=20)),
                ('bookName', models.CharField(max_length=60)),
                ('bookId', models.BigIntegerField()),
                ('progress', models.IntegerField()),
                ('readTime', models.IntegerField()),
                ('readCount', models.IntegerField()),
                ('startTime', models.BigIntegerField()),
                ('endTime', models.BigIntegerField()),
                ('wordCount', models.BigIntegerField()),
                ('pageCount', models.IntegerField()),
            ],
            options={
                'db_table': 'readprogress',
                'verbose_name': '\u9605\u8bfb\u8fdb\u5ea6',
                'verbose_name_plural': '\u9605\u8bfb\u8fdb\u5ea6',
            },
        ),
    ]
