# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-27 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookid', models.CharField(default=1, max_length=50, verbose_name=b'\xe5\x9b\xbe\xe4\xb9\xa6\xe7\xbc\x96\xe5\x8f\xb7')),
                ('username', models.CharField(max_length=30, verbose_name=b'\xe7\x94\xa8\xe6\x88\xb7\xe5\x90\x8d')),
                ('newsname', models.CharField(blank=True, max_length=50, null=True, verbose_name=b'\xe6\x96\xb0\xe9\x97\xbb\xe6\xa0\x87\xe9\xa2\x98')),
                ('booksname', models.CharField(blank=True, max_length=50, null=True, verbose_name=b'\xe4\xb8\x8a\xe4\xbc\xa0\xe5\x9b\xbe\xe4\xb9\xa6\xe5\x90\x8d')),
                ('status', models.CharField(blank=True, max_length=10, verbose_name=b'\xe5\x9b\xbe\xe4\xb9\xa6\xe7\x8a\xb6\xe6\x80\x81')),
                ('url', models.CharField(default=1, max_length=100, verbose_name=b'\xe5\x9b\xbe\xe4\xb9\xa6\xe4\xb8\x8b\xe8\xbd\xbd\xe5\x9c\xb0\xe5\x9d\x80')),
                ('md5', models.CharField(blank=True, max_length=128, verbose_name=b'\xe5\x9b\xbe\xe4\xb9\xa6md\xe5\x80\xbc')),
            ],
            options={
                'db_table': 'wechat',
                'verbose_name': '\u7528\u6237',
                'verbose_name_plural': '\u7528\u6237',
            },
        ),
        migrations.CreateModel(
            name='User1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookid', models.CharField(max_length=50, verbose_name=b'\xe4\xb9\xa6\xe7\xb1\x8did')),
                ('booksname', models.CharField(max_length=50, verbose_name=b'\xe4\xb9\xa6\xe5\x90\x8d')),
                ('serial', models.CharField(max_length=50, verbose_name=b'\xe7\xbb\x88\xe7\xab\xaf\xe5\xba\x8f\xe5\x88\x97\xe5\x8f\xb7')),
                ('url', models.CharField(max_length=100, verbose_name=b'\xe5\x9b\xbe\xe4\xb9\xa6\xe4\xb8\x8b\xe8\xbd\xbd\xe5\x9c\xb0\xe5\x9d\x80')),
                ('status', models.CharField(default=False, max_length=10, verbose_name=b'\xe5\x9b\xbe\xe4\xb9\xa6\xe4\xb8\x8b\xe8\xbd\xbd\xe7\x8a\xb6\xe6\x80\x81')),
            ],
            options={
                'db_table': 'obook',
                'verbose_name': '\u56fd\u6587',
                'verbose_name_plural': '\u56fd\u6587',
            },
        ),
        migrations.CreateModel(
            name='User2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=50, verbose_name=b'\xe7\xbb\x88\xe7\xab\xaf\xe5\xba\x8f\xe5\x88\x97\xe5\x8f\xb7')),
                ('weid', models.CharField(blank=True, max_length=50, null=True, verbose_name=b'\xe7\x94\xa8\xe6\x88\xb7openid')),
                ('bind', models.CharField(default=0, max_length=10, verbose_name=b'\xe7\xbb\x91\xe5\xae\x9a\xe7\x8a\xb6\xe6\x80\x81')),
                ('scene_id', models.CharField(max_length=32, verbose_name=b'scend_id')),
            ],
            options={
                'db_table': 'tobind',
                'verbose_name': '\u7ed1\u5b9a',
                'verbose_name_plural': '\u7ed1\u5b9a',
            },
        ),
        migrations.CreateModel(
            name='User3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booksname', models.CharField(max_length=50, verbose_name=b'\xe6\x8e\xa8\xe9\x80\x81\xe4\xb9\xa6\xe5\x90\x8d')),
                ('serial', models.CharField(default=0, max_length=50, verbose_name=b'\xe7\xbb\x88\xe7\xab\xaf\xe5\xba\x8f\xe5\x88\x97\xe5\x8f\xb7')),
            ],
            options={
                'db_table': 'booksend',
                'verbose_name': '\u63a8\u9001\u4e66\u7c4d',
                'verbose_name_plural': '\u63a8\u9001\u4e66\u7c4d',
            },
        ),
    ]
