# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-28 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='url',
            field=models.CharField(default=1, max_length=200, verbose_name=b'\xe5\x9b\xbe\xe4\xb9\xa6\xe4\xb8\x8b\xe8\xbd\xbd\xe5\x9c\xb0\xe5\x9d\x80'),
        ),
    ]
