# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-28 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0002_auto_20180828_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user3',
            name='booksname',
        ),
        migrations.AddField(
            model_name='user3',
            name='bookid',
            field=models.CharField(default=1, max_length=50, verbose_name=b'\xe6\x8e\xa8\xe9\x80\x81\xe4\xb9\xa6\xe7\xb1\x8d\xe7\xbc\x96\xe5\x8f\xb7'),
        ),
    ]
