# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-09 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0003_auto_20180928_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='User4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=50, verbose_name=b'\xe7\xbb\x88\xe7\xab\xaf\xe5\xba\x8f\xe5\x88\x97\xe5\x8f\xb7')),
                ('weid', models.CharField(blank=True, max_length=50, verbose_name=b'\xe7\x94\xa8\xe6\x88\xb7openid')),
            ],
            options={
                'db_table': 'sewe',
                'verbose_name': '\u7b80\u5355\u7ed1\u5b9a',
                'verbose_name_plural': '\u7b80\u5355\u7ed1\u5b9a',
            },
        ),
    ]
